### ISSUE TITLE
Improve SQL by using the placeholders

### ISSUE THREAD

**Issue by tmuras** [johndimopoulos/moodle-gradingform_erubric#4]
In several places in renderer.php, SQL is created by concatenating the variables instead of using the placeholders and prepared statements. Example:

```
$sql = "SELECT COUNT(fp.id) AS TOTALS
          FROM {forum_posts} fp
           INNER JOIN {forum_discussions} fdcs ON (fp.discussion = fdcs.id)
             WHERE   fp.userid IN ($participatingstudents)
                   AND fdcs.course = $courseid
                   AND fdcs.forum = $instanceid ";
```

It would be better from the security perspective to change those into [placeholders](https://docs.moodle.org/dev/Security:SQL_injection).

**Comment by johndimopoulos** [comment]
Thank you very much for your input Tomasz, I will try to look into it as soon as possible, even though I had thought about it when I first created this plugin 8 years ago. It couldn't be done properly then, due to the complexity of the queries and the code used in moodle at that time, but it could be a good improvement for new updates, so I will consider your advice. Thank you!
