### ISSUE TITLE
Not compatible with postgrsql

### ISSUE THREAD

**Issue by hamzakhalem** [johndimopoulos/moodle-gradingform_erubric#7]
the plugin queries in renderer.php are not compatible with postgresql 
![MicrosoftTeams-image](https://github.com/johndimopoulos/moodle-gradingform_erubric/assets/72972114/3a20709f-a73e-477a-b20f-3e25019b5489)

**Comment by johndimopoulos** [comment]
Thank you for your observation. I will attempt to fix this as soon as possible.

**Comment by johndimopoulos** [comment]
Hello again,

This bug was addressed 5 years ago (@see https://github.com/johndimopoulos/moodle-gradingform_erubric/issues/5 ). The final version of the plugin here on github, has the appropriate fixes. The final version on moodle.org wasn't updated (sorry that was my mistake). Version 4.0 of this plugin is on the way, where everything will be in order. So, download the v.3.0 (Master version) of LAeR from here and you won't have any issues.

Sorry for the inconvenience,

Awaiting your reply...

**Comment by hamzakhalem** [comment]
@johndimopoulos  thank you, good luck for the new version . and if any help required i will be happy to give some
